using System.Collections.Generic;
using System.Text;
using FridayCodingIDE.Models;

namespace FridayCodingIDE.Services
{
    public static class LuaGenerator
    {
        public static string GenerateFromScene(List<FNFObjectData> objects)
        {
            StringBuilder lua = new StringBuilder();
            lua.AppendLine("-- Generated by Friday-Coding IDE");
            lua.AppendLine();
            lua.AppendLine("function onCreate()");
            
            foreach (var obj in objects)
            {
                lua.AppendLine($"    -- Object: {obj.Tag}");
                lua.AppendLine($"    makeLuaSprite('{obj.Tag}', '{obj.ImagePath}', {obj.Position.X}, {obj.Position.Y});");
                
                if (obj.Scale.X != 1.0f || obj.Scale.Y != 1.0f)
                {
                    lua.AppendLine($"    scaleObject('{obj.Tag}', {obj.Scale.X}, {obj.Scale.Y});");
                }

                if (obj.Alpha != 1.0f)
                {
                    lua.AppendLine($"    setProperty('{obj.Tag}.alpha', {obj.Alpha});");
                }

                if (obj.Camera != "camGame")
                {
                    lua.AppendLine($"    setObjectCamera('{obj.Tag}', '{obj.Camera}');");
                }

                lua.AppendLine($"    addLuaSprite('{obj.Tag}', true);");
                lua.AppendLine();
            }

            lua.AppendLine("end");
            return lua.ToString();
        }
    }
}
