name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore FridayCodingIDE.Desktop/FridayCodingIDE.Desktop.csproj
    - name: Build
      run: dotnet build FridayCodingIDE.Desktop/FridayCodingIDE.Desktop.csproj --no-restore
    - name: Test
      run: dotnet test FridayCodingIDE.Desktop/FridayCodingIDE.Desktop.csproj --no-build --verbosity normal
